- name: Push files to a Git repository
  hosts: all
  vars:
    repo_path: /tmp/test
    commit_message: "Automated commit from Ansible playbook"
    branch_name: "main"
    commit_message: "Automated commit via Ansible playbook"
    git_username: "{{ lookup('env','GIT_USER') | default('') }}"
    git_password: "{{ lookup('env','GIT_PASS') | default('') }}"
    repo_url: "https://{{ git_username }}:{{ git_password }}@github.com/anandpavithran/myscap.git"


  tasks:
    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present
    - name: Clone repository if not present (SSH auth)
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_path }}"
        version: "{{ branch_name }}"
        accept_hostkey: yes
        update: yes
    - name: Copy file
      ansible.builtin.copy:
        content: "Hello World"
        dest: {{repo_path}}/sample.txt    

    - name: Change to repo directory and pull latest changes
      ansible.builtin.command: git pull
      args:
        chdir: "{{ repo_path }}"

    - name: Add all changes to git
      ansible.builtin.command: git add .
      args:
        chdir: "{{ repo_path }}"

    - name: Commit changes
      ansible.builtin.command: git commit -m "{{ commit_message }}"
      args:
        chdir: "{{ repo_path }}"
      register: git_commit
      #failed_when: git_commit.rc != 0 and "'nothing to commit'" not in git_commit.stderr

    - name: Push changes to remote repository
      ansible.builtin.command: git push
      args:
        chdir: "{{ repo_path }}"

